version: '3.9'
services:
  remix-app:
    container_name: remix-app
    image: remix-app:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    networks:
      - remix-app-nw
    ports:
      - '3000:3000'

networks:
  remix-app-nw:
